spring.application.name=tache-service
#connexion à MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/taches-db

# (optionnel) Activer les logs des requêtes MongoDB
logging.level.org.springframework.data.mongodb.core.MonogoTemplate=DEBUG

server.port=8081

spring.cloud.discovery.enabled=true
management.endpoints.web.exposure.include=*
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false